/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loading;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prajawal
 */
public class Billdetails extends javax.swing.JFrame {
    Connection con=null;
  Statement st=null;
  PreparedStatement pst=null;
  ResultSet rs=null;
  static String id;

    /**
     * Creates new form Billdetails
     */
    public Billdetails() {
        initComponents();
         try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","root123");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
         Logger.getLogger(CustomerCheckout.class.getName()).log(Level.SEVERE, null, ex);
     }
         showDataInTable();
    }
         public void showDataInTable(){
     try {
         pst=con.prepareStatement("select* from customer where status=? ");
         pst.setString(1, "Null");
         rs=pst.executeQuery();
        ResultSetMetaData obj=  (ResultSetMetaData) rs.getMetaData();
         int n=obj.getColumnCount();
         DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
         df.setRowCount(0);
         while(rs.next()){
             Vector v=new Vector();
             for(int i=1;i<n;i++){
                 v.add
                         (rs.getString("billid"));
                  v.add(rs.getString("name"));
                  v.add(rs.getString("mobile"));
                  v.add(rs.getString("gender"));
                  v.add(rs.getString("email"));
                  v.add(rs.getString("id"));
                  v.add(rs.getString("date"));
                  v.add(rs.getString("outdate"));
                  v.add(rs.getString("price")); 
                  v.add(rs.getString("days")); 
                  v.add(rs.getString("amount")); 
                 
             }
             df.addRow(v);
         }
         
         
         
     } catch (SQLException ex) {
         Logger.getLogger(CustomerCheckout.class.getName()).log(Level.SEVERE, null, ex);
     }
    
         
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txtoutdate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Bill id", "Room Number", "Customer name", "Mobile Number", "Gender", "Nationnality", "Adhaar Number", "Check in Date", "Check outDate", "price", "Number of days", "Total Amount"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1090, 531));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("W:\\hotelmanagement\\Customer Details Bill.png")); // NOI18N
        jLabel1.setText("Customer BillDetails");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 236, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Search by Checkout");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 128, 147, 22));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 129, 95, 25));

        txtoutdate.setBackground(new java.awt.Color(255, 0, 51));
        txtoutdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtoutdate.setForeground(new java.awt.Color(255, 255, 255));
        txtoutdate.setText("Search");
        txtoutdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoutdateActionPerformed(evt);
            }
        });
        getContentPane().add(txtoutdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 127, 93, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 127, 100, -1));

        jButton3.setIcon(new javax.swing.ImageIcon("W:\\hotelmanagement\\close.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1081, 0, 20, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Double Click on row to open bill");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 11, 236, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon("W:\\hotelmanagement\\admin Home.png")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtoutdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoutdateActionPerformed
 try {
         pst=con.prepareStatement("select* from customer where status=? and outdate=?");
         pst.setString(1, "Null");
                  pst.setString(2, txtoutdate.getText());
         rs=pst.executeQuery();
        ResultSetMetaData obj=  (ResultSetMetaData) rs.getMetaData();
         int n=obj.getColumnCount();
         DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
         df.setRowCount(0);
         while(rs.next()){
             Vector v=new Vector();
             for(int i=1;i<n;i++){
                 v.add
                         (rs.getString("billid"));
                 
                     v.add(rs.getString("roomnumber"));
                  v.add(rs.getString("name"));
                  v.add(rs.getString("mobile"));
                  v.add(rs.getString("gender"));
                  v.add(rs.getString("Nationality"));
                  v.add(rs.getString("id"));
                  v.add(rs.getString("date"));
                  v.add(rs.getString("outdate"));
                  v.add(rs.getString("price")); 
                  v.add(rs.getString("days")); 
                  v.add(rs.getString("amount")); 
                 
             }
             df.addRow(v);
         }
         
         
         
     } catch (SQLException ex) {
         Logger.getLogger(CustomerCheckout.class.getName()).log(Level.SEVERE, null, ex);
     }
    

        // TODO add your handling code here:
    }//GEN-LAST:event_txtoutdateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
showDataInTable ();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
if(evt.getClickCount()==2){
    
 DefaultTableModel df=(DefaultTableModel) jTable1.getModel();
    id=(String) df.getValueAt(jTable1.getSelectedRow(), 0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton txtoutdate;
    // End of variables declaration//GEN-END:variables
}
