/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loading;


//import com.mysql.cj.jdbc.result.ResultSetMetaData;
//import com.mysql.cj.jdbc.result.ResultSetMetaData;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prajawal
 */
public class CustomerCheckout extends javax.swing.JFrame {
 Connection con=null;
  Statement st=null;
  PreparedStatement pst=null;
  ResultSet rs=null;
    /**
     * Creates new form CustomerCheckout
     */
    public CustomerCheckout() {
        initComponents();
         SimpleDateFormat obj=new SimpleDateFormat("yyyy/MM/dd");
        Date date=new Date();
        txtoutdate.setText(obj.format(date));
        try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","root123");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
         Logger.getLogger(CustomerCheckout.class.getName()).log(Level.SEVERE, null, ex);
     }
        showDataInTable();
    }
    public void showDataInTable(){
     try {
         pst=con.prepareStatement("select* from customer where status=? ");
         pst.setString(1, "Null");
         rs=pst.executeQuery();
        ResultSetMetaData obj=  (ResultSetMetaData) rs.getMetaData();
         int n=obj.getColumnCount();
         DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
         df.setRowCount(0);
         while(rs.next()){
             Vector v=new Vector();
             for(int i=1;i<n;i++){
                 v.add
                         (rs.getString("name"));
                  v.add(rs.getString("mobile"));
                  v.add(rs.getString("id"));
                  v.add(rs.getString("roomnumber"));
                  v.add(rs.getString("bed"));
                  v.add(rs.getString("roomtype"));
                  v.add(rs.getString("date"));
                  v.add(rs.getString("price"));
                  v.add(rs.getString("address")); 
                 
             }
             df.addRow(v);
         }
         
         
         
     } catch (SQLException ex) {
         Logger.getLogger(CustomerCheckout.class.getName()).log(Level.SEVERE, null, ex);
     }
    
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtroomno = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtadhaarno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtoutdate = new javax.swing.JTextField();
        txtmobnumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtindate = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtdays = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon("W:\\hotelmanagement\\exit.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1063, 0, 37, 34));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("W:\\hotelmanagement\\Customer Check Out.png")); // NOI18N
        jLabel1.setText("Customer Checkout");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 22, 200, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Amount");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, 130, 27));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Price per day");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 202, 119, 28));
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 244, 170, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Room Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));
        getContentPane().add(txtroomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 66, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 100, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Check in Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 114, 28));
        getContentPane().add(txtadhaarno, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 160, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Mobile Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 822, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Adhaar Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 130, 28));
        getContentPane().add(txtoutdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, 150, -1));
        getContentPane().add(txtmobnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Check out date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 108, -1));

        txtindate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtindateActionPerformed(evt);
            }
        });
        getContentPane().add(txtindate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 170, -1));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 154, 170, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer Name", "Mobile Number", "Adhaar Number", "Room Number", "Bed type", "Room type", "Check in Date", "Bill id", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 385, 1100, 390));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Check Out Now");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 314, -1, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 314, 73, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 822, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Customer Name");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 116, 130, 27));
        getContentPane().add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 100, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Total no of days");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 130, 27));
        getContentPane().add(txtdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 100, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("W:\\hotelmanagement\\admin Home.png")); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 770));

        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtindateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtindateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtindateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        try {
         pst=con.prepareStatement("select * from customer where roonumber=? and status=?");
         pst.setString(1,txtroomno.getText());
pst.setString(2, "Null");
rs=pst.executeQuery();
if(rs.next()){
    txtname.setText(rs.getString("name"));
     txtmobnumber.setText(rs.getString("mobile"));
      txtadhaarno.setText(rs.getString("id"));
       txtprice.setText(rs.getString("price"));
        txtindate.setText(rs.getString("date"));
}
    
        String  s1,s2;
s1=txtoutdate.getText();
s2=rs.getString("date");
SimpleDateFormat formate=new SimpleDateFormat("yyyy/MM/dd");
Date d1=formate.parse(s1);
Date d2=formate.parse(s2);
long diff=d1.getTime()-d2.getTime();
int days=(int)diff/(24*60*60*1000);
if(days==0){
    days=1;
    txtdays.setText(String .valueOf(days));
           
    double price=Double.parseDouble(rs.getString ("price"))*days;
    txtamount.setText(String.valueOf(price));

//} catch (SQLException ex) {
        // Logger.getLogger(CustomerCheckout.class.getName()).log(Level.SEVERE, null, ex);
        }
   } catch (SQLException ex) {
         Logger.getLogger(CustomerCheckout.class.getName()).log(Level.SEVERE, null, ex);
   } catch (ParseException ex) {
         Logger.getLogger(CustomerCheckout.class.getName()).log(Level.SEVERE, null, ex);
     }
    


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
txtname.setText("");
txtmobnumber.setText("");
txtadhaarno.setText("");
txtprice.setText("");
txtdays.setText("");
txtindate.setText("");
//txtoutdate.setText("");
txtamount.setText("");


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     try {
         pst=con.prepareCall("update customer set status=? where roomnumber=? and date=?");
         pst.setString(1,"check-out");
          pst.setString(2,txtroomno.getText());
          pst.setString(3,txtindate.getText());
          pst.executeUpdate();
       pst=con.prepareCall("update room set status=? where roomnumber=? ");
        pst.setString(1,"Not booked");
         pst.setString(2,txtroomno.getText());
          pst.executeUpdate();
         JOptionPane.showMessageDialog(this,"check out successfully");
         showDataInTable();
         txtname.setText("");
txtmobnumber.setText("");
txtadhaarno.setText("");
txtprice.setText("");
txtdays.setText("");
txtindate.setText("");
//txtoutdate.setText("");
txtamount.setText("");
        // TODO add your handling code here:
     } catch (SQLException ex) {
         Logger.getLogger(CustomerCheckout.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtadhaarno;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtdays;
    private javax.swing.JTextField txtindate;
    private javax.swing.JTextField txtmobnumber;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtoutdate;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtroomno;
    // End of variables declaration//GEN-END:variables
}
