/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loading;
import java.util.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Prajawal
 */
public class CustomerCheckin extends javax.swing.JFrame {
    Connection con=null;
  Statement st=null;
  PreparedStatement pst=null;
  ResultSet rs=null;

    /**
     * Creates new form CustomerCheckin
     */
    public CustomerCheckin()  {
        initComponents();
        SimpleDateFormat obj=new SimpleDateFormat("yyyy/MM/dd");
        Date date=new Date();
        txtdate.setText(obj.format(date));
       
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","root123");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
            Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
        }
            prajwal();
            }
    public void prajwal(){
        try {
            pst=con.prepareStatement("Select  roomnumber from room where bed=? and roomtype=? and status=?");
            pst.setString(1,combobed.getItemAt(combobed.getSelectedIndex()));
            pst.setString(2,comboroomtype.getItemAt(comboroomtype.getSelectedIndex()));
            pst.setString(3,"Not Booked");
            rs=pst.executeQuery();
            txtroomnumber.removeAllItems();
            while(rs.next()){
                txtroomnumber.addItem(rs.getString("roomnumber"));
            }
            pst=con.prepareStatement("select price from room where roomnumber=?");
               pst.setString(1,txtroomnumber.getItemAt(txtroomnumber.getSelectedIndex()));
               rs=pst.executeQuery();
               if(rs.next())
                   txtprice.setText(rs.getString("price"));
                   
        } catch (SQLException ex) {
            Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtmobile = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combogender = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtnat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        combobed = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        comboroomtype = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        btncheckin = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        txtroomnumber = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtadhaar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon("W:\\hotelmanagement\\exit.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1065, 0, 35, 35));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading/Customer Registration & Check IN.png"))); // NOI18N
        jButton2.setText("Customer Checkin");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 22, 223, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 121, 223, 24));

        txtname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 151, 223, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mobile Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 189, 223, -1));

        txtmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobileActionPerformed(evt);
            }
        });
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 214, 223, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 264, 223, -1));

        combogender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combogender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male ", "Female", "Other" }));
        getContentPane().add(combogender, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 296, 223, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nationality");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 334, 223, -1));

        txtnat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtnat, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 366, 223, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Room Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 404, 223, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Check InDate");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 192, -1));

        txtdate.setEditable(false);
        txtdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 214, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Bed Type");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 201, 214, -1));

        combobed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combobed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", " " }));
        combobed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobedItemStateChanged(evt);
            }
        });
        combobed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobedActionPerformed(evt);
            }
        });
        getContentPane().add(combobed, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 233, 214, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Room type");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 271, 214, -1));

        comboroomtype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ac", "Non-Ac", " " }));
        comboroomtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboroomtypeItemStateChanged(evt);
            }
        });
        getContentPane().add(comboroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 303, 214, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Price");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 357, 214, -1));

        txtprice.setEditable(false);
        txtprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 222, -1));

        btncheckin.setBackground(new java.awt.Color(0, 204, 153));
        btncheckin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncheckin.setText("Checkin now");
        btncheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckinActionPerformed(evt);
            }
        });
        getContentPane().add(btncheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, -1, 42));

        btnclear.setBackground(new java.awt.Color(0, 204, 153));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, 73, 42));

        txtroomnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtroomnumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 220, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Adhaar Number");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 220, 30));
        getContentPane().add(txtadhaar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 220, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("W:\\hotelmanagement\\admin Home.png")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1110, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobileActionPerformed

    private void combobedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobedActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void txtroomnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtroomnumberActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_txtroomnumberActionPerformed

    private void comboroomtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboroomtypeItemStateChanged
prajwal();        // TODO add your handling code here:
    }//GEN-LAST:event_comboroomtypeItemStateChanged

    private void combobedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobedItemStateChanged
prajwal();        // TODO add your handling code here:
    }//GEN-LAST:event_combobedItemStateChanged

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
txtname.setText("");
txtmobile.setText("");
txtadhaar.setText("");
txtnat.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void btncheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckinActionPerformed
if(txtname.getText().equals("")){
    txtname.requestFocus();
JOptionPane.showMessageDialog(this,"all feild are required");// TODO add your handling code here:
    }//GEN-LAST:event_btncheckinActionPerformed
if(txtmobile.getText().equals("")){
    txtmobile.requestFocus();
JOptionPane.showMessageDialog(this,"all feild are required");// TODO add your handling code here:
    }    
if(txtadhaar.getText().equals("")){
    txtadhaar.requestFocus();
JOptionPane.showMessageDialog(this,"all feild are required");// TODO add your handling code here:
    }  
if(txtnat.getText().equals("")){
    txtnat.requestFocus();
JOptionPane.showMessageDialog(this,"all feild are required");// TODO add your handling code here:
    } 
else{
    try {
        pst=con.prepareStatement("insert into customer(Name,mobile,gender,id,nationality,joineddate,roomnumber,bed,roomtype,price,status)values(?,?,?,?,?,?,?,?,?,?,?)");
   pst.setString(1,txtname.getText());
     pst.setString(2,txtmobile.getText());
      pst.setString(3,combogender.getItemAt(combogender.getSelectedIndex()));
       pst.setString(4,txtadhaar.getText());
        pst.setString(5,txtnat.getText());
         pst.setString(6,txtdate.getText());
          pst.setString(7,txtroomnumber.getItemAt(txtroomnumber.getSelectedIndex()));
           pst.setString(8,comboroomtype.getItemAt(comboroomtype.getSelectedIndex()));
            pst.setString(9,combobed.getItemAt(combobed.getSelectedIndex()));
     pst.setString(10,txtprice.getText());
     pst.setString(11,"Null");
     pst.executeUpdate();
     JOptionPane.showMessageDialog(this,"Customer checked in successfully");
     txtname.setText("");
txtmobile.setText("");
txtadhaar.setText("");
txtnat.setText("");
pst=con.prepareStatement("update room set status=? where roomnumber=?");
pst.setString(1,"Booked");
pst.setString(2,txtroomnumber.getItemAt(txtroomnumber.getSelectedIndex()));
pst.executeUpdate();
prajwal();
            
    } catch (SQLException ex) {
        Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncheckin;
    private javax.swing.JButton btnclear;
    private javax.swing.JComboBox<String> combobed;
    private javax.swing.JComboBox<String> combogender;
    private javax.swing.JComboBox<String> comboroomtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtadhaar;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnat;
    private javax.swing.JTextField txtprice;
    private javax.swing.JComboBox<String> txtroomnumber;
    // End of variables declaration//GEN-END:variables
}
